version: "3.8"

services:
  api:
    container_name: mime-api
    build: ./api

    volumes:
      - ./api:/app:Z
      - ${VIDEO_SRC_FOLDER:?}:/videos
      - ./web-extras:/extras

    environment:
      DB_HOST: db
      DB_PORT: 5432
      PUBLIC_API_BASE: /api

      DB_NAME: ${DB_NAME:?}
      DB_USER: ${DB_USER:?}
      DB_PASSWORD: ${DB_PASSWORD:?}
      JUPYTER_TOKEN: ${JUPYTER_PASSWORD:?}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      VIDEO_SRC_FOLDER: /videos

    depends_on:
      - db

    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf'

  web-ui:
    container_name: mime-web-ui
    build: ./web-ui

    volumes:
      - ./web-ui:/app:Z

    environment:
      PUBLIC_API_BASE: /api

  db:
    container_name: mime-db
    image: ankane/pgvector
    shm_size: 1g

    volumes:
      - mime-db-data:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: ${DB_NAME:?}
      POSTGRES_USER: ${DB_USER:?}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?}

  web-extras:
    container_name: mime-web-extras
    build: ./web-extras

    volumes:
      - ./web-extras:/app

    stop_grace_period: 0s

  web-proxy:
    container_name: mime-web-proxy
    image: nginx:alpine
    ports:
      - ${APP_HOST:-127.0.0.1}:${APP_PORT:-8080}:80

    volumes:
      - ./nginx.config:/etc/nginx/conf.d/default.conf

    depends_on:
      - api
      - web-extras
      - web-ui

    stop_grace_period: 0s

volumes:
  mime-db-data:
