[tool.black]
line-length = 89
target-version = ['py310']

[tool.ruff]
extend-exclude = ["notebooks", "lib/yolox"]
ignore = []
line-length = 89
select = ["B","C","E","F","T","W","B9","I"]
src = ["api"]

[tool.ruff.isort]
known-first-party = ["lib", "mime_db"]
known-local-folder = ["api"]
